name: acter_avatar
description: Avatars as used by Acter.global. Supports various shapes of avatars UI.
version: 2.0.0+5
homepage: https://github.com/acterglobal/acter-avatar

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  multiavatar: ^0.1.5
  logging: ^1.2.0
  freezed: ^2.5.2

dev_dependencies:
  build_runner: ^2.4.9
  flutter_test:
    sdk: flutter

